import i18n from '@/i18n'

export const myProjects = [
  {
    title: 'Farmácias APP',
    description: i18n.t('projects.farmaciasapp'),
    technologies: [
      'Next JS',
      'TypeScript',
      'JavaScript',
      'Styled Components',
      'Radix',
      'Axios',
      'Nookies',
      'UUID',
      'React Lottie',
      'React Places Autocomplete',
      'React Google Maps',
      'Iconsax',
      'JWT',
      'YUP',
      'UI-Kit Fapp',
    ],
    image: '/assets/farmaciasapp.webp',
    link: 'https://www.fappdev.com/home',
    i18n: 'farmaciasapp',
  },
  {
    title: 'Rapid Resume',
    description: i18n.t('projects.rapidResume'),
    technologies: [
      'Next 14',
      'TypeScript',
      'Axios',
      'Tailwind CSS',
      'Clerk',
      'Zustand',
      'React Hook Form',
      'Shadcn UI',
    ],
    image: '/assets/rapid-resume.webp',
    link: 'https://rapid-resume.adrielgama.dev/',
    projectLink: 'https://github.com/adrielgama/rapid-resume',
    i18n: 'rapidResume',
    development: true,
  },
  {
    title: 'Blag - Dashboard',
    description: i18n.t('projects.blag'),
    technologies: [
      'Next 14',
      'TypeScript',
      'Axios',
      'Next Auth',
      'Tailwind CSS',
      'Tinymce',
      'Google Recaptcha',
      'React Query (TanStack Query)',
      'React Hook Form',
      'Shadcn UI',
      'ZOD',
    ],
    image: '/assets/blag-dashboard.webp',
    link: 'https://blag.adrielgama.dev/',
    projectLink: 'https://github.com/adrielgama/blag-dashboard',
    i18n: 'blag',
  },
  {
    title: 'Blag - API',
    description: i18n.t('projects.blag'),
    technologies: [
      'Prisma',
      'Express',
      'Axios',
      'Postgres',
      'TypeScript',
      'Jsonwebtoken',
      'Marked',
      'Node-cron',
      'Redis',
      'UUID',
      'Swagger',
      'Cors',
      'Bcrypt',
      'Bull',
      'Railway',
    ],
    image: '/assets/api.webp',
    link: 'https://api.adrielgama.dev/',
    projectLink: 'https://github.com/adrielgama/blag-api',
    i18n: 'blag',
  },
  {
    title: 'Josiane Mendonça - Lawyer',
    description: i18n.t('projects.josianeMendonca'),
    technologies: [
      'TypeScript',
      'Vite',
      'Tailwind',
      'Shadcn',
      'Emotion',
      'React Awesome Reveal',
      'EmailJS',
      'Axios',
      'React Hook Form',
      'React Query',
      'ZOD',
    ],
    image: '/assets/josiane-mendonca.webp',
    link: 'https://www.josianemendonca.adv.br/',
    projectLink: 'https://github.com/adrielgama/josianemendonca.adv',
    i18n: 'josianeMendonca',
  },
  {
    title: 'UI-Kit Farmácias APP',
    description: i18n.t('projects.uiKitFarmaciasApp'),
    technologies: [
      'React JS',
      'TypeScript',
      'Storybook',
      'Styled Components',
      'NPM',
      'Jest',
      'Prism React Renderer',
      'ESLint',
      'Markdown',
      'Iconsax',
      'Husky',
      'React Lottie',
    ],
    image: '/assets/ui-kit-farmaciasapp.webp',
    link: 'https://ui-kit.poc.fappdev.com/',
    i18n: 'uiKitFarmaciasApp',
  },
  {
    title: 'Onboarding - Farmácias APP',
    description: i18n.t('projects.onboardingFarmaciasApp'),
    technologies: [
      'Vite',
      'TypeScript',
      'Tailwind',
      'Shadcn',
      'ESLint',
      'Context API',
      'Azure',
    ],
    image: '/assets/onboarding-farmaciasapp.webp',
    link: 'https://onboarding.farmaciasapp.com.br/',
    i18n: 'onboardingFarmaciasApp',
  },
  {
    title: 'Tapetes & Tal',
    description: i18n.t('projects.tapetesETal'),
    technologies: [
      'Vite',
      'React JS',
      'TypeScript',
      'Tailwind',
      'Shadcn',
      'React Marquee',
      'EmailJS',
      'React Hook Form',
      'ZOD',
      'Zustand',
      'Vercel Analytics',
      'Microsoft Clarity',
    ],
    image: '/assets/tapetes-e-tal.webp',
    link: 'https://www.tapetesetal.com.br/',
    i18n: 'tapetesETal',
  },
]
