export const myProjects = [
  {
    title: 'Farmácias APP',
    description:
      'Pharmacy delivery, supplements, hygiene products, and makeup.',
    technologies: [
      'Next JS',
      'TypeScript',
      'JavaScript',
      'Styled Components',
      'Radix',
      'Axios',
      'Nookies',
      'UUID',
      'React Lottie',
      'React Places Autocomplete',
      'React Google Maps',
      'Iconsax',
      'JWT',
      'YUP',
      'UI-Kit Fapp',
    ],
    image: '/src/assets/farmaciasapp.webp',
    link: 'https://www.farmaciasapp.com.br/',
  },
  {
    title: 'Josiane Mendonça - Lawyer',
    description:
      'Professional platform for a labor lawyer, offering legal services and representation in labor law, with information about her experience, areas of practice, and contact details.',
    technologies: [
      'TypeScript',
      'Vite',
      'Tailwind',
      'Shadcn',
      'Emotion',
      'React Awesome Reveal',
      'EmailJS',
      'Axios',
      'React Hook Form',
      'React Query',
      'ZOD',
    ],
    image: '/src/assets/josiane-mendonca.webp',
    link: 'https://www.josianemendonca.adv.br/',
  },
  {
    title: 'Blag - Dashboard',
    description:
      'If you are looking for a complete dashboard for creating posts and articles that provides the response as an api, this is your best choice.',
    technologies: [
      'Vite',
      'TypeScript',
      'Axios',
      'Marked',
      'Nookies',
      'React Google Recaptcha',
      'Tailwind',
      'Tinymce',
      'Cloudinary',
      'ZOD',
    ],
    image: '/src/assets/blag-dashboard.webp',
    link: 'https://blag.adrielgama.dev/',
  },
  {
    title: 'Blag - API',
    description:
      'If you are looking for a complete dashboard for creating posts and articles that provides the response as an api, this is your best choice.',
    technologies: [
      'Prisma',
      'Express',
      'Axios',
      'Postgres',
      'TypeScript',
      'Jsonwebtoken',
      'Marked',
      'Node-cron',
      'Redis',
      'UUID',
      'Swagger',
      'Cors',
      'Bcrypt',
      'Bull',
      'Railway',
    ],
    image: '/src/assets/api.webp',
    link: 'https://github.com/adrielgama/blag-api',
  },
  {
    title: 'UI-Kit Farmácias APP',
    description:
      'Design System/UI-Kit of Farmácias APP group provides guidelines, components, and templates to enhance the user experience of their products.',
    technologies: [
      'React JS',
      'TypeScript',
      'Storybook',
      'Styled Components',
      'NPM',
      'Jest',
      'Prism React Renderer',
      'ESLint',
      'Markdown',
      'Iconsax',
      'Husky',
      'Jest',
      'React Lottie',
    ],
    image: '/src/assets/ui-kit-farmaciasapp.webp',
    link: 'https://ui-kit.poc.fappdev.com/',
  },
  {
    title: 'Tapetes & Tal',
    description:
      'Site for a company dedicated to the sale of customized carpets of various types.',
    technologies: [
      'Next JS',
      'TypeScript',
      'Tailwind',
      'Shadcn',
      'Emotion',
      'React Reveal',
      'React Slick',
      'EmailJS',
      'React Hook Form',
      'ZOD',
      'React Fast Marquee',
    ],
    image: '/src/assets/tapetes-e-tal.webp',
    link: 'https://www.tapetesetal.com.br/',
  },
]
